# Stage 1: Builder
FROM python:3.12 AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Stage 2: Runtime (small image)
FROM python:3.12-slim
WORKDIR /app

# copy installed packages from builder
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# copy your source code
COPY . .

EXPOSE 5000
CMD ["python", "app.py"]
